Gemfile:
  optional:
    ':extra':
      - gem: 'plist'
        version: '~> 3.1.0'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
.travis.yml:
  secure: "cQXCjI2KnP9iWbB6wYTRuxSFNNJ9iZQeIPghdtg/8AWffI/YRLn9vRnxT9pu45j9mU0E3xYdd991k1fz7a4eY++ITW71+b4OJYj6bRawUfB4Y3/mFUfiggkMsZ2Kw5zjSqh0dNdGIvg8mi1EszpGSpyLIX8UTmxznbGJndV4GNxuUUruN406FfOPD/9HjbSUX+88qKpBVmgMt2i7lxKYFk8pPYT7+SCj8tAiZ6vpk2ymjmqwWUhlEJUGBbpGPuJ8KH3SjScCOl7Yibbdd4rR4gbXXFfx27vaWB7XwETYgDYBJSQO5cSp/S/WEg168ELY90usMiKkKcECe+fDa3/ckBYtq3XqwPjDHZkxsnlBqnLPbPbldonewIhSRqHXM+eh86teY5AP8OTGoseSm5XTcb6FNYwItuufvrUpJiDUtunDBW1R1NGDgOwJxhJ+tQtXTL3mSSDOCrnAcGiYTN7htOze5puRMnOFeEf+BGExvv4SOALMmpF+YJSMlWRi4yYsqJ0BYqvJuRH/dH3FM9Zs9RU6nzBmyd7qQPqd0jylt/zCdRP5wJF07urLrh6XhV9p7UbZnoEe+yZuc04QntjedqlLFvdXncTFB14t10JBWatXsTD2zQkZhBwHj58r3tfao2QfgYFGHKKotaqufIkiJW76fwjd26rjVy4tPc76I98="
