Gemfile:
  optional:
    ':extra':
      - gem: 'plist'
        version: '~> 3.1.0'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
